sudo: required

services:
    - docker

before_install:
    - docker build -t kaiserlautern/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kaiserlautern/docker-react npm run test 