name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci 
      - name: check code formatting
        run: npm run format:check
      - name: run tests
        run: npm run test -- --code-coverage
        env:
          CI: true 
